version: '3.8'

services:
  # Simple training service
  drone-rl:
    build: .
    container_name: drone-rl
    volumes:
      - ./runs:/app/runs
      - ./models:/app/models
      - ./results:/app/results
      - ${HOME}/Documents/AirSim:/home/drone/Documents/AirSim
    ports:
      - "6006:6006"  # TensorBoard
      - "8888:8888"  # Jupyter (if needed)
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    runtime: nvidia
    command: ["python", "train_ppo.py"]

  # TensorBoard for monitoring
  tensorboard:
    build: .
    container_name: tensorboard
    volumes:
      - ./runs:/app/runs:ro
    ports:
      - "6007:6006"
    command: ["tensorboard", "--logdir=/app/runs", "--host=0.0.0.0"]